name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@master

    - name: Build
      run: make dist -j2

    - uses: actions/upload-artifact@master
      with:
        name: sigpatch-updater
        path: sigpatch-updater.zip
